### ISSUE TITLE
关于Binwalk

### ISSUE THREAD

**Issue by MingDeee** [ProbiusOfficial/CTF-OS#23]
Windows里使用binwalk出现报错。
首先进行安装：进入`C:\HelloCTF\Toolkit\隐写工具\图片类\binwalk-2.3.4>`，` python setup.py install`
然后进入`C:\Environment\Python38\Scripts>`，使用`python binwalk XXX.jpg`
出现如下报错：
```
binwalk:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('binwalk==2.3.3', 'binwalk')
Traceback (most recent call last):
  File "binwalk", line 4, in <module>
    __import__('pkg_resources').run_script('binwalk==2.3.3', 'binwalk')
  File "C:\Environment\Python38\lib\site-packages\pkg_resources\__init__.py", line 691, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Environment\Python38\lib\site-packages\pkg_resources\__init__.py", line 1530, in run_script
    exec(code, namespace, namespace)
  File "c:\environment\python38\lib\site-packages\binwalk-2.3.3-py3.8.egg\EGG-INFO\scripts\binwalk", line 2, in <module>
    from binwalk.__main__ import main
  File "C:\Environment\Python38\lib\site-packages\binwalk-2.3.3-py3.8.egg\binwalk\__main__.py", line 24, in <module>
    import binwalk.modules
  File "C:\Environment\Python38\lib\site-packages\binwalk-2.3.3-py3.8.egg\binwalk\modules\__init__.py", line 16, in <module>
    from binwalk.modules.extractor import Extractor
  File "C:\Environment\Python38\lib\site-packages\binwalk-2.3.3-py3.8.egg\binwalk\modules\extractor.py", line 7, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

```

官方解释：https://github.com/ReFirmLabs/binwalk/issues/594

**Comment by ProbiusOfficial** [comment]
binwalk集成在 wsl Ubuntu 中.



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2024年4月22日(週一) 下午4:44
收件人： ***@***.***&gt;;
抄送： ***@***.***&gt;;
主旨： [ProbiusOfficial/CTF-OS] 关于Binwalk (Issue #23)




 
Windows里使用binwalk出现报错。
 首先进行安装：进入C:\HelloCTF\Toolkit\隐写工具\图片类\binwalk-2.3.4&gt;， python setup.py install
 然后进入C:\Environment\Python38\Scripts&gt;，使用python binwalk XXX.jpg
 出现如下报错：
 binwalk:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html   __import__('pkg_resources').run_script('binwalk==2.3.3', 'binwalk') Traceback (most recent call last):   File "binwalk", line 4, in <module&gt;     __import__('pkg_resources').run_script('binwalk==2.3.3', 'binwalk')   File "C:\Environment\Python38\lib\site-packages\pkg_resources\__init__.py", line 691, in run_script     self.require(requires)[0].run_script(script_name, ns)   File "C:\Environment\Python38\lib\site-packages\pkg_resources\__init__.py", line 1530, in run_script     exec(code, namespace, namespace)   File "c:\environment\python38\lib\site-packages\binwalk-2.3.3-py3.8.egg\EGG-INFO\scripts\binwalk", line 2, in <module&gt;     from binwalk.__main__ import main   File "C:\Environment\Python38\lib\site-packages\binwalk-2.3.3-py3.8.egg\binwalk\__main__.py", line 24, in <module&gt;     import binwalk.modules   File "C:\Environment\Python38\lib\site-packages\binwalk-2.3.3-py3.8.egg\binwalk\modules\__init__.py", line 16, in <module&gt;     from binwalk.modules.extractor import Extractor   File "C:\Environment\Python38\lib\site-packages\binwalk-2.3.3-py3.8.egg\binwalk\modules\extractor.py", line 7, in <module&gt;     import pwd ModuleNotFoundError: No module named 'pwd'  
官方解释：ReFirmLabs/binwalk#594
